server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
#        make a list of routes with -,
#        specify the id, the uri has to be lb://MICROSERVICE_NAME like the one that shows in eureka server
#        or under the property spring.application.name and predicates is the path to the base url of the controller
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
